std = "lua51"
max_line_length = false
exclude_files = { "Libs/", ".luarocks/", "lua_modules/" }
-- Addon methods (FS:Foo) often don't use self.
self = false

-- WoW API used by the addon. Keep sorted; add as modules grow.
read_globals = {
	"Ambiguate",
	"bit",
	"ButtonFrameTemplate_HidePortrait",
	"C_AddOns",
	"C_Club",
	"C_GuildInfo",
	"C_Item",
	"C_Map",
	"C_MerchantFrame",
	"C_SuperTrack",
	"C_Texture",
	"C_Timer",
	"CANCEL",
	"CanEditGuildInfo",
	"ChatEdit_InsertLink",
	"ChatFrameUtil",
	"CreateDataProvider",
	"CreateFrame",
	"CreateScrollBoxListLinearView",
	"date",
	"Enum",
	"GameTooltip",
	"GameTooltip_Hide",
	"GetBuildInfo",
	"GetGuildInfo",
	"GetGuildInfoText",
	"GetGuildRosterInfo",
	"GetItemInfo",
	"GetMerchantItemCostInfo",
	"GetMerchantItemCostItem",
	"GetMerchantItemInfo",
	"GetMerchantItemLink",
	"GetMerchantNumItems",
	"GetNormalizedRealmName",
	"GetNumGuildMembers",
	"GetServerTime",
	"GetTime",
	"GuildControlGetNumRanks",
	"GuildControlGetRankName",
	"HBD_PINS_WORLDMAP_SHOW_CONTINENT",
	"hooksecurefunc",
	"InCombatLockdown",
	"IsControlKeyDown",
	"IsInGuild",
	"IsInInstance",
	"issecretvalue",
	"IsShiftKeyDown",
	"LibStub",
	"MenuUtil",
	"MerchantFrame",
	"Minimap",
	"NO",
	"ScrollBoxConstants",
	"ScrollUtil",
	"StaticPopup_Show",
	"tinsert",
	"TomTom",
	"TooltipDataProcessor",
	"UIErrorsFrame",
	"UiMapPoint",
	"UIParent",
	"UISpecialFrames",
	"UnitClassification",
	"UnitExists",
	"UnitFullName",
	"UnitGUID",
	"UnitIsPlayer",
	"UnitName",
	"wipe",
	"WorldMapFrame",
	"YES",
}

-- Globals the addon defines or fills in.
globals = {
	"BINDING_HEADER_FRONTIERSCOUT",
	"BINDING_NAME_FRONTIERSCOUT_ADD",
	"BINDING_NAME_FRONTIERSCOUT_BROWSER",
	"FrontierScout_AddBinding",
	"FrontierScout_OnAddonCompartmentClick",
	"FrontierScout_ToggleBinding",
	"StaticPopupDialogs",
}

files["tests/"] = {
	std = "+busted",
	self = false,
	read_globals = { "setfenv" },
}
